services:
  - type: web
    name: pryMongoEsp32
    runtime: python
    repo: https://github.com/AsaelitoTapia/Proyecto_Mongo_ESP32
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://asael_tapia:<leasa1234>@cluster0.ko5kj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
version: "1"
